name: gradient_generator
description: >
  A developer-friendly Flutter package to generate and apply beautiful gradients
  with a clean Dart API and ready-to-use widgets.
version: 1.0.0
homepage: https://github.com/the-anurag-codes/gradient_generator
repository: https://github.com/the-anurag-codes/gradient_generator
issue_tracker: https://github.com/the-anurag-codes/gradient_generator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
